from __future__ import absolute_import, division, print_function, unicode_literals

import curses
import ntpath
import os
import sys
import textwrap

def add_beast_to_path():
  python_home = os.path.join(os.getcwd(), 'python')
  if python_home not in sys.path:
    sys.path.append(python_home)

add_beast_to_path()

from beast.util import Terminal
from beast.util.Tests import run_tests

ENVIRONMENT_VARIABLES = {
  'BOOST_HOME': None,
  'CC': '',
  'CCFLAGS': '',
  'CFLAGS': '',
  'CPPFLAGS': None,
  'CXX': 'clang++',
  'CXXFLAGS': '-x c++ -stdlib=libc++ -std=c++11 -frtti -g',
  'LIBPATH': '',
  'LIBS': '',
  'LINKFLAGS': '-stdlib=libc++',
  }

VARIANT_DIRECTORIES = {
    'beast': ('bin', 'beast'),
    'modules': ('bin', 'modules'),
}

MAIN_PROGRAM_FILE = 'beast/unit_test/tests/main.cpp'
FIELD_WIDTH = 10

NAME_VALUE_PAIR_FORMAT = '%s \033[94m%s\033[0m'
COMMAND_LINE_FORMAT = '           \033[94m%s\033[0m'
EMPTY_NAME = ' ' * FIELD_WIDTH

TEXT_WRAPPER = textwrap.TextWrapper(
    break_long_words=False,
    break_on_hyphens=False,
    width=69,
)

DISPLAY_EMPTY_ENVS = True
BOOST_HOME = 'BOOST_HOME'

def is_string(s):
  return isinstance(s, (str, unicode))

def boost_path():
    try:
      path = os.environ[BOOST_HOME]
      if path:
        return path
    except KeyError:
      pass
    raise KeyError('%s environment variable is not set.' % BOOST_HOME)

def join_items(items, joiner=''):
    return joiner.join(str(i) for i in items or ())

def print_build_vars(env, name, value):
    """Pretty-print values as a build configuration."""
    name = '%s' % name.rjust(FIELD_WIDTH)

    if not is_string(value):
        value = join_items(value, ' ')

    for line in TEXT_WRAPPER.wrap(value):
        print(' '.join([name, Terminal.blue(line)]))
        name = EMPTY_NAME

def print_build_config(env):
    print('\nConfiguration:')
    for name, default in ENVIRONMENT_VARIABLES.items():
        value = env.get(name)
        if value or DISPLAY_EMPTY_ENVS:
           print_build_vars(env, name, value)
    print()

def print_cmd_line(s, target, source, env):
    print(COMMAND_LINE_FORMAT % join_items(target))

def make_env():
    env = Environment()

    env['PRINT_CMD_LINE_FUNC'] = print_cmd_line

    for name, path in VARIANT_DIRECTORIES.items():
        env.VariantDir(os.path.join(*path), name, duplicate=0)

    # Copy important os environment variables into env
    replacements = {}
    for name, default in ENVIRONMENT_VARIABLES.items():
        value = os.environ.get(name, default)
        if value:
            replacements[name] = value
    env.Replace(**replacements)
    env['CCCOMSTR'] = 'Compiling $TARGET'
    env['LINKCOMSTR'] = 'Linking $TARGET'
    boost = boost_path()
    env.Prepend(CPPPATH=boost)
    env.Append(LIBPATH=os.path.join(boost, 'stage', 'lib'))

    return env

def main():
    env = make_env()
    print_build_config(env)
    run_tests(env, MAIN_PROGRAM_FILE, '.', '.test.cpp')

main()
